#!/usr/bin/env bash
#
# provision-linux.sh - prepare a Linux node for the mesh cross-machine suite.
#
# Runs ON the Linux node, invoked from the Windows driver as:
#     ssh <host> 'bash -s' < provision-linux.sh <commit-sha>
#
# It NEVER touches an existing checkout. A bare mirror is kept at MIRROR_DIR and
# each commit is materialized as its own git worktree under CLONES_DIR, so a
# user's working tree, its branch, and its uncommitted changes are never
# reached. Re-provisioning the same commit is a no-op.
#
# Environment overrides:
#     MIRROR_DIR  bare mirror location       (default $HOME/dsh-mesh-mirror.git)
#     CLONES_DIR  per-commit worktrees root  (default $HOME/dsh-mesh-clones)
#     HOME_DIR    DSH_HOME for the test node (default $HOME/dsh-mesh-home)
#     REPO_URL    git remote                 (default the upstream repository)
#
set -euo pipefail

MIRROR_DIR="${MIRROR_DIR:-$HOME/dsh-mesh-mirror.git}"
CLONES_DIR="${CLONES_DIR:-$HOME/dsh-mesh-clones}"
HOME_DIR="${HOME_DIR:-$HOME/dsh-mesh-home}"
REPO_URL="${REPO_URL:-https://github.com/deepseek-ai/deepseek-harness.git}"
WEB_PORT="${WEB_PORT:-3081}"
# T1: the mesh binds a unix socket, so there is no local TCP port to connect to.
MESH_SOCKET="${MESH_SOCKET:-/run/user/$(id -u)/dsh-mesh.sock}"
# 8444, not 8443: the reference machine already publishes 8443 to 127.0.0.1:8765.
PUBLISHED_PORT="${PUBLISHED_PORT:-8444}"
MESH_PATH="${MESH_PATH:-/mesh/v1}"
DISPLAY_NAME="${DISPLAY_NAME:-linux-node}"
SHA="${1:-}"

if [ -z "$SHA" ]; then
  echo "usage: provision-linux.sh <commit-sha>" >&2
  exit 2
fi

log() { printf '%s %s\n' "[provision]" "$*"; }

# ---- 0. refuse obviously unsafe locations --------------------------------

case "$MIRROR_DIR$CLONES_DIR$HOME_DIR" in
  */.git/*|*/.git) echo "ERROR: refusing to operate inside a .git directory" >&2; exit 1 ;;
esac
if [ "$MIRROR_DIR" = "$CLONES_DIR" ]; then
  echo "ERROR: MIRROR_DIR and CLONES_DIR must differ" >&2
  exit 1
fi

# ---- 1. runtime ------------------------------------------------------------

command -v node >/dev/null 2>&1 || { echo "ERROR: node is not installed; the harness needs Node ^22.19 || >=24" >&2; exit 1; }
NODE_VERSION="$(node --version)"
log "node $NODE_VERSION"
case "$NODE_VERSION" in
  v22.19.*|v22.[2-9][0-9].*|v2[3-9].*|v[3-9][0-9].*) ;;
  *) echo "ERROR: node $NODE_VERSION does not satisfy ^22.19 || >=24" >&2; exit 1 ;;
esac
command -v pnpm >/dev/null 2>&1 || { echo "ERROR: pnpm is not installed" >&2; exit 1; }
log "pnpm $(pnpm --version)"

# ---- 2. a dedicated worktree, never an existing checkout -------------------

REPO_DIR="$CLONES_DIR/$SHA"

if [ ! -d "$MIRROR_DIR" ]; then
  log "creating bare mirror at $MIRROR_DIR"
  git clone --bare --filter=blob:none "$REPO_URL" "$MIRROR_DIR"
fi
git --git-dir="$MIRROR_DIR" fetch --quiet --prune origin

if [ ! -f "$REPO_DIR/.provisioned" ]; then
  if [ -e "$REPO_DIR" ]; then
    echo "ERROR: $REPO_DIR exists but is not a provisioned clone; remove it by hand" >&2
    exit 1
  fi
  log "creating worktree at $REPO_DIR for $SHA"
  mkdir -p "$CLONES_DIR"
  git --git-dir="$MIRROR_DIR" worktree add --detach "$REPO_DIR" "$SHA"

  cd "$REPO_DIR"
  log "installing workspace dependencies"
  pnpm install --frozen-lockfile
  log "building (the slow step)"
  pnpm run build
  echo "$SHA" > .provisioned
  log "provisioned $SHA"
else
  cd "$REPO_DIR"
  if [ "$(cat .provisioned)" != "$SHA" ]; then
    echo "ERROR: $REPO_DIR is provisioned for $(cat .provisioned), not $SHA" >&2
    exit 1
  fi
  log "already provisioned at $SHA"
fi

# A worktree must be clean: the suite asserts against committed code only.
if [ -n "$(git status --porcelain)" ]; then
  echo "ERROR: $REPO_DIR has local modifications; the suite must run against committed code" >&2
  git status --short >&2
  exit 1
fi

# ---- 3. harness home and the mesh composition ------------------------------

mkdir -p "$HOME_DIR/profiles/web"

cat > "$HOME_DIR/profiles/web/cordis.patch.yml" <<YAML
# Generated by provision-linux.sh - the mesh test node composition.
# The GUI stays on loopback; only the mesh listener is published.
- insert:
    - id: mesh
      name: '@deepseek-ai/dsh-mesh'
      config:
        displayName: $DISPLAY_NAME
        auditFailurePolicy: refuse-writes
    - id: mesh-tailscale
      name: '@deepseek-ai/dsh-mesh/tailscale'
    - id: mesh-ops
      name: '@deepseek-ai/dsh-mesh-ops'
    - id: mesh-agent
      name: '@deepseek-ai/dsh-mesh-agent'
      config:
        enabled: true
        # T1: a unix socket fronted by tailscale serve. No local TCP port exists,
        # so no local process can bypass serve and forge advisory headers.
        listen:
          kind: unix
          path: $MESH_SOCKET
        pathPrefix: $MESH_PATH
        publishedScheme: https
        publishedPort: $PUBLISHED_PORT
    - id: mesh-remote
      name: '@deepseek-ai/dsh-mesh-remote'
    - id: api-mesh-controller
      name: '@deepseek-ai/dsh-api-mesh-controller'
YAML

log "wrote $HOME_DIR/profiles/web/cordis.patch.yml"

# ---- 4. publish the mesh listener on the tailnet ---------------------------

mkdir -p "$(dirname "$MESH_SOCKET")"
if tailscale serve --bg --https="$PUBLISHED_PORT" "unix:$MESH_SOCKET" >/dev/null 2>&1; then
  log "published https://<this-node>:$PUBLISHED_PORT -> unix:$MESH_SOCKET via tailscale serve"
else
  log "WARNING: tailscale serve failed (HTTPS certificates may be disabled for this tailnet)."
  log "WARNING: either enable certificates or switch this node to topology T3 (listen kind: tailscale)."
fi

if tailscale serve status 2>&1 | grep 'Funnel on' -A 50 | grep -q ":$PUBLISHED_PORT\b"; then
  echo "ERROR: mesh port $PUBLISHED_PORT is Funnel-exposed to the public internet." >&2
  echo "       run: tailscale funnel --https=$PUBLISHED_PORT off" >&2
  exit 1
fi

# ---- 5. report -------------------------------------------------------------

log "done"
log "start the node with:"
log "  DSH_HOME=$HOME_DIR dsh --profile web --no-open --port $WEB_PORT"
log "the GUI binds 127.0.0.1:$WEB_PORT and must stay unreachable from other machines."
log "repo: $REPO_DIR"
